<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK6myJsI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK6myJsI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK6myJsI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK6myJsI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK6myJsI\App_KernelDevDebugContainer([
    'container.build_hash' => 'K6myJsI',
    'container.build_id' => '19bf1322',
    'container.build_time' => 1766359088,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK6myJsI');
