<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin_hotels_list' => [[], ['_controller' => 'App\\Controller\\Api\\Admin\\HotelController::list'], [], [['text', '/api/admin/hotels']], [], [], []],
    'admin_hotels_rooms' => [['id'], ['_controller' => 'App\\Controller\\Api\\Admin\\HotelController::rooms'], [], [['text', '/rooms'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/admin/hotels']], [], [], []],
    'admin_maintenance_create' => [[], ['_controller' => 'App\\Controller\\Api\\Admin\\MaintenanceController::create'], [], [['text', '/api/admin/maintenance']], [], [], []],
    'admin_maintenance_list_by_room' => [['id'], ['_controller' => 'App\\Controller\\Api\\Admin\\MaintenanceController::listByRoom'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/admin/maintenance/rooms']], [], [], []],
    'admin_maintenance_update' => [['id'], ['_controller' => 'App\\Controller\\Api\\Admin\\MaintenanceController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/admin/maintenance']], [], [], []],
    'admin_rooms_show' => [['id'], ['_controller' => 'App\\Controller\\Api\\Admin\\RoomController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/admin/rooms']], [], [], []],
    'admin_services_list' => [[], ['_controller' => 'App\\Controller\\Api\\Admin\\ServiceController::list'], [], [['text', '/api/admin/services']], [], [], []],
    'client_reservation_create' => [[], ['_controller' => 'App\\Controller\\Api\\Client\\ReservationController::create'], [], [['text', '/api/client/reservations']], [], [], []],
    'client_reservation_delete' => [['id'], ['_controller' => 'App\\Controller\\Api\\Client\\ReservationController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/client/reservations']], [], [], []],
    'App\Controller\Api\Admin\HotelController::list' => [[], ['_controller' => 'App\\Controller\\Api\\Admin\\HotelController::list'], [], [['text', '/api/admin/hotels']], [], [], []],
    'App\Controller\Api\Admin\HotelController::rooms' => [['id'], ['_controller' => 'App\\Controller\\Api\\Admin\\HotelController::rooms'], [], [['text', '/rooms'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/admin/hotels']], [], [], []],
    'App\Controller\Api\Admin\MaintenanceController::create' => [[], ['_controller' => 'App\\Controller\\Api\\Admin\\MaintenanceController::create'], [], [['text', '/api/admin/maintenance']], [], [], []],
    'App\Controller\Api\Admin\MaintenanceController::listByRoom' => [['id'], ['_controller' => 'App\\Controller\\Api\\Admin\\MaintenanceController::listByRoom'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/admin/maintenance/rooms']], [], [], []],
    'App\Controller\Api\Admin\MaintenanceController::update' => [['id'], ['_controller' => 'App\\Controller\\Api\\Admin\\MaintenanceController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/admin/maintenance']], [], [], []],
    'App\Controller\Api\Admin\RoomController::show' => [['id'], ['_controller' => 'App\\Controller\\Api\\Admin\\RoomController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/admin/rooms']], [], [], []],
    'App\Controller\Api\Admin\ServiceController::list' => [[], ['_controller' => 'App\\Controller\\Api\\Admin\\ServiceController::list'], [], [['text', '/api/admin/services']], [], [], []],
    'App\Controller\Api\Client\ReservationController::create' => [[], ['_controller' => 'App\\Controller\\Api\\Client\\ReservationController::create'], [], [['text', '/api/client/reservations']], [], [], []],
    'App\Controller\Api\Client\ReservationController::delete' => [['id'], ['_controller' => 'App\\Controller\\Api\\Client\\ReservationController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/client/reservations']], [], [], []],
];
