<?php

namespace ContainerDUnUn86;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TvLxtV6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TvLxtV6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TvLxtV6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'App\\Controller\\Api\\Admin\\HotelController::list' => ['privates', '.service_locator.7EuUAC4', 'get_ServiceLocator_7EuUAC4Service', true],
            'App\\Controller\\Api\\Admin\\HotelController::rooms' => ['privates', '.service_locator.4ZSeJKJ', 'get_ServiceLocator_4ZSeJKJService', true],
            'App\\Controller\\Api\\Admin\\MaintenanceController::create' => ['privates', '.service_locator.5IPnQwp', 'get_ServiceLocator_5IPnQwpService', true],
            'App\\Controller\\Api\\Admin\\MaintenanceController::listByRoom' => ['privates', '.service_locator.P2Z5_jE', 'get_ServiceLocator_P2Z5JEService', true],
            'App\\Controller\\Api\\Admin\\MaintenanceController::update' => ['privates', '.service_locator.M2O8cDB', 'get_ServiceLocator_M2O8cDBService', true],
            'App\\Controller\\Api\\Admin\\RoomController::show' => ['privates', '.service_locator.4ZSeJKJ', 'get_ServiceLocator_4ZSeJKJService', true],
            'App\\Controller\\Api\\Admin\\ServiceController::list' => ['privates', '.service_locator.OfazTMa', 'get_ServiceLocator_OfazTMaService', true],
            'App\\Controller\\Api\\Client\\ReservationController::create' => ['privates', '.service_locator.hPfj8rT', 'get_ServiceLocator_HPfj8rTService', true],
            'App\\Controller\\Api\\Client\\ReservationController::delete' => ['privates', '.service_locator.P7x8kSs', 'get_ServiceLocator_P7x8kSsService', true],
            'App\\Controller\\Api\\RegisterController::register' => ['privates', '.service_locator.j3kKXma', 'get_ServiceLocator_J3kKXmaService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'App\\Controller\\Api\\Admin\\HotelController:list' => ['privates', '.service_locator.7EuUAC4', 'get_ServiceLocator_7EuUAC4Service', true],
            'App\\Controller\\Api\\Admin\\HotelController:rooms' => ['privates', '.service_locator.4ZSeJKJ', 'get_ServiceLocator_4ZSeJKJService', true],
            'App\\Controller\\Api\\Admin\\MaintenanceController:create' => ['privates', '.service_locator.5IPnQwp', 'get_ServiceLocator_5IPnQwpService', true],
            'App\\Controller\\Api\\Admin\\MaintenanceController:listByRoom' => ['privates', '.service_locator.P2Z5_jE', 'get_ServiceLocator_P2Z5JEService', true],
            'App\\Controller\\Api\\Admin\\MaintenanceController:update' => ['privates', '.service_locator.M2O8cDB', 'get_ServiceLocator_M2O8cDBService', true],
            'App\\Controller\\Api\\Admin\\RoomController:show' => ['privates', '.service_locator.4ZSeJKJ', 'get_ServiceLocator_4ZSeJKJService', true],
            'App\\Controller\\Api\\Admin\\ServiceController:list' => ['privates', '.service_locator.OfazTMa', 'get_ServiceLocator_OfazTMaService', true],
            'App\\Controller\\Api\\Client\\ReservationController:create' => ['privates', '.service_locator.hPfj8rT', 'get_ServiceLocator_HPfj8rTService', true],
            'App\\Controller\\Api\\Client\\ReservationController:delete' => ['privates', '.service_locator.P7x8kSs', 'get_ServiceLocator_P7x8kSsService', true],
            'App\\Controller\\Api\\RegisterController:register' => ['privates', '.service_locator.j3kKXma', 'get_ServiceLocator_J3kKXmaService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Api\\Admin\\HotelController::list' => '?',
            'App\\Controller\\Api\\Admin\\HotelController::rooms' => '?',
            'App\\Controller\\Api\\Admin\\MaintenanceController::create' => '?',
            'App\\Controller\\Api\\Admin\\MaintenanceController::listByRoom' => '?',
            'App\\Controller\\Api\\Admin\\MaintenanceController::update' => '?',
            'App\\Controller\\Api\\Admin\\RoomController::show' => '?',
            'App\\Controller\\Api\\Admin\\ServiceController::list' => '?',
            'App\\Controller\\Api\\Client\\ReservationController::create' => '?',
            'App\\Controller\\Api\\Client\\ReservationController::delete' => '?',
            'App\\Controller\\Api\\RegisterController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Api\\Admin\\HotelController:list' => '?',
            'App\\Controller\\Api\\Admin\\HotelController:rooms' => '?',
            'App\\Controller\\Api\\Admin\\MaintenanceController:create' => '?',
            'App\\Controller\\Api\\Admin\\MaintenanceController:listByRoom' => '?',
            'App\\Controller\\Api\\Admin\\MaintenanceController:update' => '?',
            'App\\Controller\\Api\\Admin\\RoomController:show' => '?',
            'App\\Controller\\Api\\Admin\\ServiceController:list' => '?',
            'App\\Controller\\Api\\Client\\ReservationController:create' => '?',
            'App\\Controller\\Api\\Client\\ReservationController:delete' => '?',
            'App\\Controller\\Api\\RegisterController:register' => '?',
        ]);
    }
}
