<?php

namespace ContainerK6myJsI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HPfj8rTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hPfj8rT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hPfj8rT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'roomRepository' => ['privates', 'App\\Repository\\RoomRepository', 'getRoomRepositoryService', true],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'em' => '?',
            'roomRepository' => 'App\\Repository\\RoomRepository',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
        ]);
    }
}
